### ISSUE TITLE
[BUG] GitHub action doesn't fail even though cog check does

### ISSUE THREAD

**Issue by mbehr1** [cocogitto/cocogitto-action#1]
**Describe the bug**
Even though the commit message pushed/tested lets cog check fail the GitHub action succeeds.

**To Reproduce**
See here: https://github.com/mbehr1/adlt/runs/4753498724?check_suite_focus=true

**Expected behavior**
Action should fail if cog check fails.

**Additional context**
Seems as if the "shell=bash" used is set to shell: /usr/bin/sh -e {0} so will always return 0?

**Comment by oknozor** [comment]
Hey @mbehr1 this is fixed already in the latest github action version:  cocogitto/cocogitto-action@v2.1.
Also you need to update your cog.toml file to match the latest version config (see: [the config reference](https://docs.cocogitto.io/config/#general). You can also take a look at [cocogitto's config](https://github.com/cocogitto/cocogitto/blob/main/cog.toml). 

I am closing this, don't hesitate to reopen if this does not work for you.

**Comment by mbehr1** [comment]
@oknozor thx! Yep, that's working now :-) 
Btw: I changed to "uses: cocogitto/cocogitto-action@v2" and not to "uses: oknozor/cocogitto-...". Is that correct?
(Now I still struggle with the --from-latest-tag not working in CI. But will investigate a little further first :-)
