### ISSUE TITLE
[BUG] Cocogitto-action crash on cocogitto 5.6.0 config file

### ISSUE THREAD

**Issue by Cyboooooorg** [cocogitto/cocogitto-action#14]
Hi everyone,

I installed cocogitto 5.6.0 and did a `cog init` in my project.
Here  the generated file :

```toml
from_latest_tag = false
ignore_merge_commits = false
generate_mono_repository_global_tag = true
branch_whitelist = []
skip_untracked = false
pre_bump_hooks = []
post_bump_hooks = []
pre_package_bump_hooks = []
post_package_bump_hooks = []

[git_hooks]

[commit_types]

[changelog]
path = "CHANGELOG.md"
authors = []

[bump_profiles]

[packages]
```

And now my github action is crashing with the following error:

```shell
Setting git user : cog-bot
Settings git user email cog@demo.org
Error: failed to parse config

    cause unknown field `skip_untracked`, expected one of `ignore_merge_commits`, `branch_whitelist`, `tag_prefix`, `pre_bump_hooks`, `post_bump_hooks`, `commit_types`, `changelog`, `bump_profiles`

Error: Process completed with exit code 1.
```

I suggest that cocogitto-action must ignore the new field or be updated to use cocogitto 5.6.0 😄

**Comment by oknozor** [comment]
Hey, I will update the action to use the latest cocogitto version as soon as possible. Sorry for the inconvenience.

**Comment by nagyben** [comment]
I have also raised https://github.com/cocogitto/cocogitto-action/pull/15 as sanity check to see which version of cog is being run

**Comment by nagyben** [comment]
@Cyboooooorg nice catch, I also noticed that the action v3.5 is using cog v5.4.0.

It's possible to use the `@main` tag for now to pick up the latest version of the action

i.e. 
```
- name: check conventional commits
  uses: cocogitto/cocogitto-action@main
                                   ^^^^
```
