### ISSUE TITLE
[FEATURE] Automatically generate changelog content for a github release

### ISSUE THREAD

**Issue by tranzystorek-io** [cocogitto/cocogitto-action#4]
For one of my projects I have configured a custom release action that, on new version tag creation, generates a cocogitto changelog and then creates a github release with that changelog.

Maybe it would be useful to have something like this incorporated here?

EDIT: [the action](https://github.com/tranzystorek-io/pakr/blob/master/.github/workflows/release.yml), for reference

**Comment by oknozor** [comment]
Actually I did something similar in the latest version: https://github.com/cocogitto/cocogitto/blob/cd847de37cda51950e65d4b4868b8faa6ffcd880/.github/workflows/Release.yml#L41

FYI if you use cocogitto-action to create the version you can use a `workflow_dispatch` trigger to `cog bump` by hitting the release button. 
You can then use `${{ steps.release.outputs.version }}` to get the version number and generate the changelog.

**Comment by tranzystorek-io** [comment]
> Oh wait do you mean incorporating a github release upload in cocogitto-action ?

Exactly 😄

**Comment by oknozor** [comment]
I think we can just reuse the softprop action in the composite action : https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsstepsuses 
Then  bind it to some parameter to run it or not.

**Comment by tranzystorek-io** [comment]
I'm afraid this feature is too dependent on personal preference, e.g. whether you want to trigger releases in CI manually or automatically on new tag push, so without a clear use case this will only make the action harder to grok
