### ISSUE TITLE
[BUG] Action seems to use wrong conventional_commit_parser version

### ISSUE THREAD

**Issue by aeyoll** [cocogitto/cocogitto-action#7]
Hello,
I have a Gitlab action failing (https://github.com/aeyoll/wr/actions/runs/3973873822/jobs/6812797736), with the following stack stace:

```
thread 'main' panicked at 'internal error: entered unreachable code: Unexpected footer token separator : `:
`', /cargo/registry/src/github.com-1ecc6299db9ec823/conventional_commit_parser-0.9.3/src/commit.rs:68:22
```

This issue seems to be fixed in conventional_commit_parser v0.9.4, but it looks like its using an older version.

Can you take a look? Thank a lot!

**Comment by lukehsiao** [comment]
This should be fixed by https://github.com/cocogitto/cocogitto-action/commit/ac6260150ee57e3164cd95b47fc84cdee9e3444c, which was included in https://github.com/cocogitto/cocogitto-action/releases/tag/v3.5

Is this still an issue?

**Comment by oknozor** [comment]
This should be fixed now please reopen if there are any issue.
