### ISSUE TITLE
[BUG] The action cannot parse cog.toml packages entry

### ISSUE THREAD

**Issue by szattila98** [cocogitto/cocogitto-action#9]
Hi!

**Describe the bug**
I configured the action as described here. Cocogitto can verify my commits locally without problems, but when I try running the github action it says that my config is invalid, because of the [packages] entry as it is not allowed.

**To Reproduce**
Try using the action with a monorepo cog.toml config that has a [packages] entry.

**Expected behavior**
I expected that the action can parse the cog.toml and runs correctly, just as it does locally.

**Additional context**
I think it is because the action uses an older version of cocogitto.
The [log](https://github.com/szattila98/binge_at_home/actions/runs/5338221638/jobs/9675292235?pr=3) and my [action config](https://github.com/szattila98/binge_at_home/blob/project-init/.github/workflows/conventional-commits.yml).

Thanks in advance!

**Comment by szattila98** [comment]
I tried it with 3.4, and now it says that I have a merge commit which is strange, because I clearly don't have one.
https://github.com/szattila98/binge_at_home/actions/runs/5339410486/jobs/9678078800

**Comment by oknozor** [comment]
can you provide your github action files ?  I can't see them on the repo.

**Comment by szattila98** [comment]
Sure, they are on the `project-init` branch, [here](https://github.com/szattila98/binge_at_home/tree/project-init).

**Comment by oknozor** [comment]
https://github.com/cocogitto/cocogitto-action/releases/tag/v3.5
